In [1]:
%config IPCompleter.greedy=True
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data = pd.read_csv('./2016-17-to-2018-19-immunizations.csv', encoding = "ISO-8859-1")
data.head()


SCHOOL_YEAR  SCHOOL_CODE    COUNTY PUBLIC_PRIVATE       CITY  \
0   2016-2017        52749  MONTEREY        PRIVATE  PRUNEDALE   
1   2016-2017        52749  MONTEREY        PRIVATE  PRUNEDALE   
2   2016-2017        52749  MONTEREY        PRIVATE  PRUNEDALE   
3   2016-2017        52749  MONTEREY        PRIVATE  PRUNEDALE   
4   2016-2017        52749  MONTEREY        PRIVATE  PRUNEDALE   

                   SCHOOL_NAME REPORTED  ENROLLMENT    CATEGORY  COUNT  \
0  PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         PBE    NaN   
1  PRUNEDALE CHRISTIAN ACADEMY        Y        10.0        HEPB    NaN   
2  PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         DTP    NaN   
3  PRUNEDALE CHRISTIAN ACADEMY        Y        10.0       POLIO    NaN   
4  PRUNEDALE CHRISTIAN ACADEMY        Y        10.0  Up-To-Date    NaN   

   PERCENT  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN

In [3]:
data.tail()

SCHOOL_YEAR  SCHOOL_CODE        COUNTY PUBLIC_PRIVATE     CITY  \
263066   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263067   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263068   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263069   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263070   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   

              SCHOOL_NAME REPORTED  ENROLLMENT CATEGORY  COUNT  PERCENT  
263066  WOOD ROSE ACADEMY        Y        15.0      DTP    NaN      NaN  
263067  WOOD ROSE ACADEMY        Y        15.0    POLIO    NaN      NaN  
263068  WOOD ROSE ACADEMY        Y        15.0      MMR    NaN      NaN  
263069  WOOD ROSE ACADEMY        Y        15.0     HEPB    NaN      NaN  
263070  WOOD ROSE ACADEMY        Y        15.0     VARI    NaN      NaN

In [31]:
data.describe()

SCHOOL_CODE     ENROLLMENT         COUNT        PERCENT
count  2.630710e+05  253187.000000  81934.000000  207822.000000
mean   5.444149e+06      70.915351     38.144348      54.817045
std    2.111153e+06      49.893938     50.513140      46.702010
min    5.274900e+04       1.000000      0.000000       0.000000
25%    6.015416e+06      29.000000      0.000000       2.000000
50%    6.045611e+06      70.000000      4.000000      94.000000
75%    6.133714e+06     102.000000     73.000000      98.000000
max    9.915507e+06    1117.000000    916.000000      99.000000

In [4]:
data.nunique()

SCHOOL_YEAR          3
SCHOOL_CODE       8863
COUNTY              58
PUBLIC_PRIVATE       2
CITY              1077
SCHOOL_NAME       8413
REPORTED             2
ENROLLMENT         297
CATEGORY            15
COUNT              315
PERCENT            100
dtype: int64

In [5]:
data.shape

(263071, 11)

In [6]:
data.columns

Index(['SCHOOL_YEAR', 'SCHOOL_CODE', 'COUNTY', 'PUBLIC_PRIVATE', 'CITY',
       'SCHOOL_NAME', 'REPORTED', 'ENROLLMENT', 'CATEGORY', 'COUNT',
       'PERCENT'],
      dtype='object')

In [30]:
#finding and droppping duplicate rows
#TODO:: drop duplicate ? work on it
def duplicate_rows_based_on_col(df, columns): return df[df.duplicated(columns)]
duplicate_rows_based_on_col(data,['SCHOOL_YEAR','CATEGORY'])

SCHOOL_YEAR  SCHOOL_CODE        COUNTY PUBLIC_PRIVATE     CITY  \
11       2016-2017       100016        MADERA         PUBLIC   MADERA   
12       2016-2017       100016        MADERA         PUBLIC   MADERA   
13       2016-2017       100016        MADERA         PUBLIC   MADERA   
14       2016-2017       100016        MADERA         PUBLIC   MADERA   
15       2016-2017       100016        MADERA         PUBLIC   MADERA   
...            ...          ...           ...            ...      ...   
263066   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263067   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263068   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263069   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   
263070   2018-2019      9070187  CONTRA COSTA        PRIVATE  CONCORD   

                   SCHOOL_NAME REPORTED  ENROLLMENT     CATEGORY  COUNT  \
11      SHERMAN THOMAS CHARTER        Y        30.0          PME    NaN   
12      SHERMAN THOMAS CHARTER        Y        30.0          PBE    NaN   
13      SHERMAN THOMAS CHARTER        Y        30.0      Overdue    NaN   
14      SHERMAN THOMAS CHARTER        Y        30.0       Others    NaN   
15      SHERMAN THOMAS CHARTER        Y        30.0  Conditional    NaN   
...                        ...      ...         ...          ...    ...   
263066       WOOD ROSE ACADEMY        Y        15.0          DTP    NaN   
263067       WOOD ROSE ACADEMY        Y        15.0        POLIO    NaN   
263068       WOOD ROSE ACADEMY        Y        15.0          MMR    NaN   
263069       WOOD ROSE ACADEMY        Y        15.0         HEPB    NaN   
263070       WOOD ROSE ACADEMY        Y        15.0         VARI    NaN   

        PERCENT  
11          5.0  
12          5.0  
13          5.0  
14          5.0  
15          5.0  
...         ...  
263066      NaN  
263067      NaN  
263068      NaN  
263069      NaN  
263070      NaN  

[263039 rows x 11 columns]

In [8]:
# checking for garbage values in each columns

In [9]:
data['SCHOOL_YEAR'].unique()

array(['2016-2017', '2017-2018', '2018-2019'], dtype=object)

In [10]:
data['SCHOOL_CODE'].unique()

array([  52749,  100016,  100024, ..., 7337100, 7614391, 9070187],
      dtype=int64)

In [11]:
data['COUNTY'].unique()

array(['MONTEREY', 'MADERA', 'EL DORADO', 'TUOLUMNE', 'SAN BERNARDINO',
       'ALAMEDA', 'RIVERSIDE', 'SAN JOAQUIN', 'LOS ANGELES', 'VENTURA',
       'SANTA CRUZ', 'SACRAMENTO', 'CONTRA COSTA', 'SAN DIEGO', 'SUTTER',
       'KERN', 'ORANGE', 'MENDOCINO', 'STANISLAUS', 'SONOMA', 'KINGS',
       'TULARE', 'SANTA BARBARA', 'TEHAMA', 'BUTTE', 'SANTA CLARA',
       'MERCED', 'PLACER', 'FRESNO', 'SAN MATEO', 'YUBA', 'LAKE',
       'SAN LUIS OBISPO', 'NAPA', 'HUMBOLDT', 'SHASTA', 'YOLO',
       'SAN FRANCISCO', 'SOLANO', 'IMPERIAL', 'DEL NORTE', 'NEVADA',
       'SAN BENITO', 'SISKIYOU', 'LASSEN', 'MARIN', 'GLENN', 'MARIPOSA',
       'TRINITY', 'AMADOR', 'CALAVERAS', 'COLUSA', 'PLUMAS', 'ALPINE',
       'INYO', 'MODOC', 'MONO', 'SIERRA'], dtype=object)

In [12]:
data['PUBLIC_PRIVATE'].unique()

array(['PRIVATE', 'PUBLIC'], dtype=object)

In [13]:
data['CITY'].unique()

array(['PRUNEDALE', 'MADERA', 'EL DORADO HILLS', ..., 'WINDSOR HILLS',
       'OJA', 'LANCASTER,'], dtype=object)

In [14]:
data['SCHOOL_NAME'].unique()

array(['PRUNEDALE CHRISTIAN ACADEMY', 'SHERMAN THOMAS CHARTER',
       'OAK MEADOW ELEMENTARY', ...,
       'MONTESSORI ELEMENTARY AND MIDDLE SCHOOL OF TRACY',
       'TODDLER TECH UNIVERSITY',
       'CLAIRES MONTESSORI INTERNATIONAL ACADEMY'], dtype=object)

In [15]:
data['REPORTED'].unique()

array(['Y', 'N'], dtype=object)

In [16]:
data['ENROLLMENT'].unique()

array([1.000e+01, 3.000e+01, 1.270e+02, 1.000e+00, 5.600e+01, 8.300e+01,
       1.800e+01, 1.400e+02, 1.200e+02, 1.160e+02,       nan, 6.700e+01,
       1.070e+02, 5.900e+01, 1.210e+02, 1.100e+02, 9.800e+01, 9.000e+01,
       1.290e+02, 1.120e+02, 9.900e+01, 9.100e+01, 1.080e+02, 1.110e+02,
       1.300e+02, 1.130e+02, 1.500e+02, 8.100e+01, 4.000e+01, 1.370e+02,
       1.140e+02, 8.800e+01, 1.480e+02, 1.440e+02, 1.430e+02, 5.800e+01,
       1.930e+02, 1.020e+02, 9.500e+01, 8.400e+01, 4.800e+01, 4.900e+01,
       9.600e+01, 1.740e+02, 1.570e+02, 6.800e+01, 1.360e+02, 1.610e+02,
       1.560e+02, 1.240e+02, 1.200e+01, 4.000e+00, 1.420e+02, 7.800e+01,
       5.000e+01, 1.040e+02, 9.400e+01, 8.600e+01, 1.250e+02, 1.150e+02,
       1.000e+02, 7.200e+01, 1.050e+02, 1.380e+02, 1.350e+02, 1.540e+02,
       1.010e+02, 1.720e+02, 7.100e+01, 5.000e+00, 5.200e+01, 6.400e+01,
       1.530e+02, 1.230e+02, 2.160e+02, 4.500e+01, 1.090e+02, 2.000e+00,
       1.920e+02, 1.470e+02, 8.900e+01, 1.510e+02, 

In [17]:
data['CATEGORY'].unique()

array(['PBE', 'HEPB', 'DTP', 'POLIO', 'Up-To-Date', 'Others', 'VARI',
       'Conditional', 'Overdue', 'PME', 'MMR', 'CONDITIONAL', 'OTHERS',
       'OVERDUE', 'UP-TO-DATE'], dtype=object)

In [18]:
data['COUNT'].unique()

array([ nan,   0.,   2., 121., 123., 124.,   4.,   8., 128., 132., 135.,
         3., 117.,   1.,  56.,  57.,   7., 112., 114., 116., 119., 122.,
         5., 107., 108., 103., 105., 106., 109., 110., 111., 146.,  35.,
        36.,  37.,   9.,  10., 130., 134., 137., 139., 141., 131.,  12.,
        18., 143., 153., 160., 163., 166., 169., 126., 136., 100.,  90.,
        92.,  89.,  91.,   6., 165., 170., 154.,  21., 133., 138., 144.,
       147., 149., 152.,  76.,  48.,  14.,  64.,  65.,  68.,  71.,  74.,
       142., 145.,  97.,  81.,  82.,  83., 151., 167., 168.,  66.,  60.,
        61.,  62., 148., 150.,  40.,  41., 104., 185., 186., 187.,  67.,
        93.,  95.,  54.,  55.,  51.,  84., 101.,  25.,  29., 178., 182.,
       184., 191.,  17.,  85.,  49.,  96.,  98., 102.,  77.,  72.,  73.,
        24., 120.,  80.,  78., 127., 115., 157.,  63.,  69., 118.,  99.,
        58.,  26.,  27.,  28., 171., 140., 113.,  94., 278., 292., 293.,
       297., 226.,  19.,  79.,  23., 129.,  75.,  1

In [19]:
data['PERCENT'].unique()

array([nan,  5., 95.,  0.,  2., 97., 98.,  3.,  6., 91., 94., 96., 99.,
        1., 93.,  8., 88., 90.,  7., 87., 89.,  4.,  9., 74., 79., 83.,
       85., 86., 13., 82., 92., 12., 14., 62., 63., 65., 68., 71., 73.,
       11., 38., 61., 66., 67., 76., 46., 54., 17., 10., 29., 78., 80.,
       15., 60., 70., 16., 84., 20., 50., 51., 53., 56., 43., 49., 57.,
       58., 77., 81., 32., 52., 18., 75., 41., 59., 69., 31., 40., 42.,
       44., 47., 55., 19., 26., 48., 72., 64., 39., 33., 36., 37., 35.,
       45., 21., 34., 30., 27., 28., 23., 22., 24., 25.])

In [20]:
#checking null values
data.isnull().sum()

SCHOOL_YEAR            0
SCHOOL_CODE            0
COUNTY                 0
PUBLIC_PRIVATE         0
CITY                   0
SCHOOL_NAME            0
REPORTED               0
ENROLLMENT          9884
CATEGORY               0
COUNT             181137
PERCENT            55249
dtype: int64

In [21]:
# getting rows with null columns
def nans(df): return df[df.isnull().any(axis=1)]
def nans_col(df, column): return df[df[column].isnull()]

In [22]:
nans(data)

SCHOOL_YEAR  SCHOOL_CODE        COUNTY PUBLIC_PRIVATE       CITY  \
0        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
1        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
2        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
3        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
4        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
...            ...          ...           ...            ...        ...   
263066   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263067   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263068   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263069   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263070   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   

                        SCHOOL_NAME REPORTED  ENROLLMENT    CATEGORY  COUNT  \
0       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         PBE    NaN   
1       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0        HEPB    NaN   
2       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         DTP    NaN   
3       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0       POLIO    NaN   
4       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0  Up-To-Date    NaN   
...                             ...      ...         ...         ...    ...   
263066            WOOD ROSE ACADEMY        Y        15.0         DTP    NaN   
263067            WOOD ROSE ACADEMY        Y        15.0       POLIO    NaN   
263068            WOOD ROSE ACADEMY        Y        15.0         MMR    NaN   
263069            WOOD ROSE ACADEMY        Y        15.0        HEPB    NaN   
263070            WOOD ROSE ACADEMY        Y        15.0        VARI    NaN   

        PERCENT  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
...         ...  
263066      NaN  
263067      NaN  
263068      NaN  
263069      NaN  
263070      NaN  

[181137 rows x 11 columns]

In [23]:
nans_col(data, 'PERCENT')

SCHOOL_YEAR  SCHOOL_CODE        COUNTY PUBLIC_PRIVATE       CITY  \
0        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
1        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
2        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
3        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
4        2016-2017        52749      MONTEREY        PRIVATE  PRUNEDALE   
...            ...          ...           ...            ...        ...   
263066   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263067   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263068   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263069   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   
263070   2018-2019      9070187  CONTRA COSTA        PRIVATE    CONCORD   

                        SCHOOL_NAME REPORTED  ENROLLMENT    CATEGORY  COUNT  \
0       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         PBE    NaN   
1       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0        HEPB    NaN   
2       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0         DTP    NaN   
3       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0       POLIO    NaN   
4       PRUNEDALE CHRISTIAN ACADEMY        Y        10.0  Up-To-Date    NaN   
...                             ...      ...         ...         ...    ...   
263066            WOOD ROSE ACADEMY        Y        15.0         DTP    NaN   
263067            WOOD ROSE ACADEMY        Y        15.0       POLIO    NaN   
263068            WOOD ROSE ACADEMY        Y        15.0         MMR    NaN   
263069            WOOD ROSE ACADEMY        Y        15.0        HEPB    NaN   
263070            WOOD ROSE ACADEMY        Y        15.0        VARI    NaN   

        PERCENT  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
...         ...  
263066      NaN  
263067      NaN  
263068      NaN  
263069      NaN  
263070      NaN  

[55249 rows x 11 columns]